### ISSUE TITLE
Add CHANGELOG to dolphjs core

### ISSUE THREAD

**Issue by Andryrasolofomanana** [dolphjs/core#16]
Currently, the dolphjs core repository doesn't have a CHANGELOG.md file. Adding a CHANGELOG.md file will help users and contributors understand the changes and updates made to the project over time. It will provide a clear and concise overview of version updates, new features, bug fixes, and other important information.

**Proposed Solution:**
I suggest adding a CHANGELOG.md file to the dolphjs core repository. This file should follow the widely adopted format for changelogs, providing a chronological list of notable changes for each release.

**Benefits:**

Improved transparency: Having a changelog enables users and contributors to easily track changes made to the project and understand the evolution of features.
Better communication: It helps developers communicate updates and improvements to the community, which fosters collaboration and feedback.
Release documentation: The changelog serves as a centralized location to document important changes introduced in each version of dolphjs.

**Additional Notes:**

It would be beneficial to adhere to established conventions for writing changelogs, such as the [Keep a Changelog](https://keepachangelog.com/) format, to maintain consistency with other projects.
If there are any existing release notes or relevant documentation, they can be used as a reference to populate the initial entries in the CHANGELOG.md file.
Let me know if you have any questions or suggestions regarding this proposal. I'll be happy to assist further!

**Comment by Xlaez** [comment]
Granted.
